services:
  input_db:
    volumes:
      - ./sakila-schema.sql:/container-entrypoint-initdb.d/2.sql
      - ./oracle-sakila-insert-data.sql:/container-entrypoint-initdb.d/3.sql
      - ./sakila-schema-generation.sql:/container-entrypoint-initdb.d/4.sql
