default_config:
  mode: GENERATION
  target_row_number: 256

tables:

  - table_name_with_schema: "sakila.country"

  - table_name_with_schema: "sakila.city"
    target_row_number: 1_000

  - table_name_with_schema: "sakila.address"
    target_row_number: 5_000
    transformations:
      - columns: [ "location" ]
        params:
          type: formatted_string_generator
          pattern: POINT\(-?\d\d -?\d\d\)
          
        

  - table_name_with_schema: "sakila.staff"
    target_row_number: 256

  - table_name_with_schema: "sakila.customer"
    target_row_number: 10_000

  - table_name_with_schema: "sakila.actor"
    target_row_number: 1_000

  - table_name_with_schema: "sakila.film"
    target_row_number: 3_000
    transformations:
      - columns: ["rating"]
        params:
          type: "categorical_generator"
          categories:
            type: STRING
            value_source: PROVIDED
            values:
              "PG-13": 0.223
              "NC-17": 0.21
              "R": 0.195
              "PG": 0.194
              "G": 0.178

  - table_name_with_schema: "sakila.rental"
    target_row_number: 20_000

  - table_name_with_schema: "sakila.payment"
    target_row_number: 20_000

  - table_name_with_schema: "sakila.film_actor"
    target_row_number: 10_000

  - table_name_with_schema: "sakila.inventory"
    target_row_number: 10_000

table_truncation_mode: "TRUNCATE"
schema_creation_mode: DROP_AND_CREATE
cycle_resolution_strategy: "DELETE_NOT_REQUIRED"
safety_mode: "RELAXED"
