default_config:
  mode: GENERATION
  target_ratio: 2.0

table_truncation_mode: "TRUNCATE"
schema_creation_mode: "DROP_AND_CREATE"
cycle_resolution_strategy: "DELETE_NOT_REQUIRED"
safety_mode: "RELAXED"

tables:
  - table_name_with_schema: "sakila.address"
    target_row_number: 5_000
    transformations:
      - columns: [ "location" ]
        params:
          type: formatted_string_generator
          pattern: POINT\(-?\d\d -?\d\d\)
